### ISSUE TITLE
about edge[0] and edge [1] in function buildMainTrival()  in buildGraph.py

### ISSUE THREAD

**Issue by jokerlin12** [PhantomGrapes/MultiDigraphNER#1]
Hello!

In my understanding, the two functions buildMainTrival() and buildDictWithAbstractNode() in src/utils/buildGraph.py are meant to describe the edges in the constructed directed graph.

Function buildMainTrival() deals with edges regarding the sentence itself, while buildDictWithAbstractNode() regarding the gazetteers.

There are two lists named edges[0] and edges[1] in both functions. **I believe that they separately store the forward edges and backward edges in the graph**.

However, I am confused by the following lines of code (Line 7-10 in function buildMainTrival())

`

    for i in range(seqLen):
        if i > 0:
            edges[0].append([seq2node[i-1], seq2node[i], 1])
        if i < seqLen - 1:
            edges[1].append([seq2node[i], seq2node[i+1], 1])
`

It seems both edge[0] and edges[1] are storing the forward edges.

Do the edges lists in two functions mean differently?

**Comment by PhantomGrapes** [comment]
Thx, it's a bug.
