### ISSUE TITLE
Hyperparameter setting

### ISSUE THREAD

**Issue by SUDA-HLT-ywfang** [PhantomGrapes/MultiDigraphNER#2]
Hello!
        To reproduce the results of three public datasets in paper, what should I pay attention to? Do I need to change the default hyperparameter settings?

**Comment by PhantomGrapes** [comment]
There is no need to change hyperparameter. To reproduce the results, you need to collect some gazetteers which can cover more than 40% of entities in train and test data.

**Comment by SUDA-HLT-ywfang** [comment]
Thanks a lot!

**Comment by SUDA-HLT-ywfang** [comment]
Hello!
        In your paper, you use an extra indomain gazetteer of type PER for Weibo. Could you share this gazetteer please? Or tell me where I can get it.
