### ISSUE TITLE
files missing to reproduce the result

### ISSUE THREAD

**Issue by juneshi0315** [PhantomGrapes/MultiDigraphNER#4]
Hello, I am reading your paper these days and the results are outstanding. But when I run the model, I notice that the gazetteers used for OntoNotes, MSRA and Weibo NER are missing, as well as the embeddings for chars and bichars. Could you please add these files and the optimal params for reproducing the results? Thank you!

**Comment by ppIntelligence** [comment]
I have the same problem, did you resolve it?

**Comment by PhantomGrapes** [comment]
Give me your email, I'll send you.

**Comment by juneshi0315** [comment]
juneshi0315@qq.com, thank you

**Comment by xiaolitanhua** [comment]
1028339752@qq.com, thank you

**Comment by littlelittleflower** [comment]
> Give me your email, I'll send you.

1028339752@qq.com, thank you

**Comment by PhantomGrapes** [comment]
files sent.

**Comment by Pealicx** [comment]
2421780543@qq.com, thanks

**Comment by Jidi123** [comment]
Hello could u send me the same thanks! @1347402784@qq.com

**Comment by Monty-L** [comment]
Hello, I am reproducing your paper recently, but the data file does not contain the gazetteers of OntoNotes, MSRA and Weibo, as well as the embedding of chars and bichars. I hope you can share the relevant files, thank you!
1003940898@qq.com

**Comment by Jidi123** [comment]
您好，邮件我已收到，会尽快回复，谢谢。

**Comment by PirateX0** [comment]
您好，我想引用您的论文作为baseline，需要使用相同的词典进行比较，请问可以分享一下OntoNotes, MSRA和Weibo使用的词典吗？我的邮箱是295528322@qq.com

**Comment by PirateX0** [comment]
> 您好，我想引用您的论文作为baseline，需要使用相同的词典进行比较，请问可以分享一下OntoNotes, MSRA和Weibo使用的词典吗？我的邮箱是[295528322@qq.com](mailto:295528322@qq.com)

已收到，感谢作者！
