### ISSUE TITLE
用gpu和不用结果不一样 

### ISSUE THREAD

**Issue by marcma7358** [PhantomGrapes/MultiDigraphNER#5]
您好，想问一下为什么用gpu和不用gpu跑的结果是不一样的呢

**Comment by PhantomGrapes** [comment]
差别大吗，结果发我看看

**Comment by HJW3536** [comment]
为什么在ecommerce数据上，用CPU和GPU出来结果差不多，都是65左右？

**Comment by HJW3536** [comment]
用GPU，未调参，从腾讯词向量中抽出所有单字符和双字符作char和bichar，复现了论文结果，甚至比文章中的结果还要高一点
